trigger:
- main

jobs:
- job: Build_and_deploy
  pool:
    vmImage: ubuntu-latest

  steps:  
   - checkout: self
     persistCredentials: true
   - script: |
       npm -v
       git config user.name "development@khanon3d.com"
       git config user.email "development@khanon3d.com"
       git tag -a TEST -m "MESSAGE"
       git diff
       git push origin HEAD:$(resources.pipeline.MyBuild.runName)    
     workingDirectory: $(Build.SourcesDirectory)   
     displayName: 'test'

#   - template: azure-pipelines-build.yml
#
#   - script: |
#       npm run pipeline:validate-version
#     displayName: 'Validate version'
#
#   - task: Npm@1
#     inputs:
#       command: 'publish'
#       verbose: true
#       publishEndpoint: 'Npm public registry - Khanon.js'
#     displayName: 'Npm publish'


