trigger:
- main

jobs:
- job: Build_and_deploy
  pool:
    vmImage: ubuntu-latest
  
  variables:
  - name: tagRelease
    value: tagTest

  steps:  
   - checkout: self
     persistCredentials: true
   - script: |
       npm -v
       git config user.name "development@khanon3d.com"
       git config user.email "development@khanon3d.com"
       git tag -a TEST -m "MESSAGE"
       git diff
       git push origin HEAD:main --force
     workingDirectory: $(Build.SourcesDirectory)   
     displayName: 'test'
   - bash: 
       echo "##vso[task.setvariable variable=tagRelease;]$(node -p "require('./package.json').version")"
     displayName: 'bash'

   - task: GitHubRelease@1
     inputs:
       gitHubConnection: 'khanon-js - access token'
       repositoryName: 'khanon-js/khanon.js'
       action: 'create'
       target: '$(Build.SourceVersion)'
       tagSource: 'userSpecifiedTag'
       tag: 'Version $(tagRelease)'
       changeLogCompareToRelease: 'lastFullRelease'
       changeLogType: 'commitBased'
#   - template: azure-pipelines-build.yml
#
#   - script: |
#       npm run pipeline:validate-version
#     displayName: 'Validate version'
#
#   - task: Npm@1
#     inputs:
#       command: 'publish'
#       verbose: true
#       publishEndpoint: 'Npm public registry - Khanon.js'
#     displayName: 'Npm publish'


