trigger:
- main

jobs:
- job: Build_and_deploy
  pool:
    vmImage: ubuntu-latest
  
  variables:
  - name: tagRelease
    value: tagTest

  steps:  
   - template: azure-pipelines-build.yml

#   - script: |
#       npm run pipeline:validate-version
#     displayName: 'Validate version'
   - task: DeleteFiles@1
     inputs:
       SourceFolder: 
       Contents: '**/*!(dist)'
       RemoveDotFiles: true
   - bash: |
       dir
     displayName: 'DIR'         
   - task: CopyFiles@2
     inputs:
       SourceFolder: 'dist'
       Contents: '**'
       TargetFolder: '.'
   - bash: |
       dir
     displayName: 'DIR'     
   - script: |
       hola
     displayName: 'STOP TEST'  

   - task: Npm@1
     inputs:
       command: 'publish'
       verbose: true
       publishEndpoint: 'Npm public registry - Khanon.js'
     displayName: 'Npm publish'
   - bash: 
       echo "##vso[task.setvariable variable=tagRelease;]$(node -p "require('./package.json').version")"
     displayName: 'Get version'
   - task: GitHubRelease@1
     inputs:
       gitHubConnection: 'khanon-js - access token'
       repositoryName: 'khanon-js/khanon.js'
       action: 'create'
       title: 'Version $(tagRelease)'
       target: '$(Build.SourceVersion)'
       tagSource: 'userSpecifiedTag'
       tag: 'v$(tagRelease)'
       changeLogCompareToRelease: 'lastFullRelease'
       changeLogType: 'commitBased'
     displayName: 'Github publish'


